<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Set-up" data-toc-modified-id="Set-up-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Set up</a></span></li><li><span><a href="#Prelimanary-Analysis" data-toc-modified-id="Prelimanary-Analysis-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Prelimanary Analysis</a></span></li><li><span><a href="#Bushfire" data-toc-modified-id="Bushfire-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Bushfire</a></span></li><li><span><a href="#Appendix" data-toc-modified-id="Appendix-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Appendix</a></span><ul class="toc-item"><li><span><a href="#Person" data-toc-modified-id="Person-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Person</a></span></li><li><span><a href="#Spearman" data-toc-modified-id="Spearman-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Spearman</a></span></li><li><span><a href="#Kendall" data-toc-modified-id="Kendall-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Kendall</a></span></li></ul></li></ul></div>

# Set up

In [4]:
from scipy.stats import pearsonr
from scipy.stats import spearmanr
from scipy.stats import kendalltau

import matplotlib.pyplot as plt

import numpy as np
import os
import pandas as pd
import json
import re, datetime
from geopy.geocoders import Nominatim

# Prelimanary Analysis

input = one industry data folder
output = print a pandas table: row = a company, column = time


the steps of processing progress:
1.

In [2]:
CFP = ['ROA1', 'ROA2', 'Operating Margin', 'Net Margin', 'Return On Equity', 
           'Current Ratio', 'Quick ratio', 'ROC', 'D/E ratio', 'EPS']

def corr_ana(industry:str, climate:str, cfp_diff:int, climate_diff:int):
    """
    :industry = one of the industry name in our list
    :climate = can be temperature or bushfire data
    #:cfp = the type of CFP
    :cfp_diff = the time difference of the cfp data
    :climate_diff = the time differecne of the climate data
    output = a pandas framework 
    """
    
    # read the data of industry
    cfp_data, state_data = read_industry(industry)
    
    # read the climate data
    climate_data = read_climate(climate)
    
    # process data
    processed_data = process_data(cfp_data, state_data, climate_data, climate, cfp_diff, climate_diff)
    
    # compute the p-value
    result = compute_p(processed_data, industry, climate, cfp_diff, climate_diff)
    
    return result
    
    
def read_industry(industry:str):
    """
    :industry = one of the industry list
    output = cfp_data, state_data
    """
    root_path = os.path.abspath(os.path.dirname(os.getcwd()))
    data_path = os.path.join(root_path, 'data')
    inds_path = os.path.join(data_path, industry)

    finc_data = []
    for file in os.listdir(inds_path):
#         print(file)
        if file.endswith('.json'):
            file_path = os.path.join(inds_path, file)
            with open(file_path, 'r') as file:
                finc_data.append(json.load(file))

    cfp_data = {}
    state_data = {}
    for i in finc_data:
        for k, v in i.items():
            try:
                if i[k]['state']:
                    cfp_data[k] = {}
                    state_data[k] = i[k]['state']
                    for cfp in CFP:
                        cfp_data[k][cfp] = pd.DataFrame.from_dict(i[k][cfp]) 
            except:
                pass
            
    return cfp_data, state_data

def read_climate(climate:str):
    """
    :climate = 'bushfire' or 'temp'
    """
    
    assert climate == 'bushfire' or climate == 'temp', "plz type 'bushfire' or 'temp'"
    
    root_path = os.path.abspath(os.path.dirname(os.getcwd()))
    data_path = os.path.join(root_path, 'data')
    
    if climate == 'bushfire':
        climate_path = os.path.join(data_path, 'climate')
        file_name = 'Wildfire_data.csv'
        file_path = os.path.join(climate_path, file_name)
        climate_data = pd.read_csv(file_path)
    else:
        climate_path = os.path.join(data_path, 'climate')
        climate_path = os.path.join(climate_path, 'US_temperature_data')
        file_name = 'original_temp_data.csv'
        file_path = os.path.join(climate_path, file_name)
        climate_data = pd.read_csv(file_path)
        
    return climate_data

def process_data(cfp_data, state_data, climate_data, climate:str, cfp_diff:int, climate_diff:int):
    
    assert climate == 'bushfire' or climate == 'temp', "plz type 'bushfire' or 'temp'"
    
    if climate == 'bushfire':
        # get the bushfire and cfp data pair to feed to correlation analysis
        pairs = process_bushfire_pairs(cfp_data, state_data, climate_data, cfp_diff, climate_diff)
    else:
        # get the temperature and cfp data pair to feed
        pairs = process_temp_pairs(cfp_data, state_data, climate_data, cfp_diff, climate_diff)
        
    return pairs

def process_temp_pairs(cfp_data, state_data, temp_data, cfp_diff:int, climate_diff:int):
    """
    :cfp_data = 
    :state_data = 
    output = a nested dict, the key is the company name, and the value is a dictionary with the four keys: 
                "cfp_data", "climate_data", "cfp_year", "climate_year", and "state", 
                the "cfp_data" and "climate_data" will feed to correlation analysis
    """
    result = {}
    
    # shape data as year, cfp, temp
    for comp in cfp_data.keys():
        # init the values
        result[comp] = {}
        state = state_data[comp]
        state_temp = temp_data.loc[temp_data['State'] == state] # get state temp date
        state_temp = state_temp.set_index("Date") # set Date as row index  
        
        for c in CFP:
            result[comp][c] = {}
            cfp = []
            temp = []
            cfp_time = []
            temp_time = []
            cfp_time = []
            # get cfp timeline 
            for i in cfp_data[comp][c].iloc[:,range(1, cfp_data[comp][c].shape[1])]:
                try:
                    i = i.split('/')
                    cfp_time.append(datetime.date(int(i[-1]), int(i[0]), int(i[1])))
                except:
                    pass        
        
            # get temp timeline
            state_temp_time = []
            for i in state_temp.index.values:
                i = i.split('/')
                state_temp_time.append(datetime.date(int(i[0]), int(i[1]), int(i[2])))     
            
            # get the temp avg
            temp_curr_avg = []
            temp_past_avg = []
            cfp_index = []
            # for each interval(elementc) in roa, we need to find the corresponding temp difference
            # the corresponding temp difference = the current avg. temp - the avg. temp over past n years in the same interval
            for time in range(len(cfp_time)-1): # don't check the last element of cfp_time    
                now = cfp_time[time]
                now_year = cfp_time[time].year
                now_month = cfp_time[time].month
                now_day = cfp_time[time].day
                try: # use exisiting data to get the interval
                    past = cfp_time[time + 1]
                    past_year = cfp_time[time + 1].year
                    past_month = cfp_time[time + 1].month
                    past_day = cfp_time[time + 1].day
                except: # assume the past year for the last element
                    # to prevent nan value situation
                    past_year = now_year - 1
                    past_month = now_month
                    past_day = now_day
                    past = datetime.date(past_year, past_month, past_day)
                temp_sum = 0
                temp_count = 0
                # get temp avg. of current year 
                for temp in range(len(state_temp_time)):
                    if past <= state_temp_time[temp] < now:
                        year = str(state_temp_time[temp].year)
                        month = str(state_temp_time[temp].month)
                        day = str(state_temp_time[temp].day)
                        timestamp = year + '/' + month + '/' + day
                        temp_sum += state_temp.loc[timestamp].values[0]
                        temp_count += 1       
                if temp_count == 0: # can't find corresponding data points
                    continue
                temp_curr_avg.append(temp_sum/temp_count)
                temp_sum = 0
                temp_count = 0
                # get temp avg. of the past n years
                for n in range(1, climate_diff+1):
                    now_year -= 1
                    past_year -= 1
                    now = datetime.date(now_year, now_month, now_day)
                    past = datetime.date(past_year, past_month, past_day)
                    for temp in range(len(state_temp_time)):
                        if past <= state_temp_time[temp] < now:
                            year = str(state_temp_time[temp].year)
                            month = str(state_temp_time[temp].month)
                            day = str(state_temp_time[temp].day)
                            timestamp = year + '/' + month + '/' + day
                            temp_sum += state_temp.loc[timestamp].values[0]
                            temp_count += 1
                if climate_diff != 0:
                    temp_past_avg.append(temp_sum/temp_count)
                else:
                    temp_past_avg.append(0)
                cfp_index.append(time)
                temp_time.append(cfp_time[time])
            columns = list(cfp_data[comp][c].columns[1:])
            # get cfp data
            for i in range(len(columns)):
                if i in cfp_index:
                    if i + cfp_diff >= len(columns):
                        # i = current cfp data point
                        # i + cfp_diff = the farest data cfp data point
                        # if count + cfp_diff is out of range, terminate computing the cfp moving avg.,
                        # otherwise the array can provide sufficient data points 
                        break
                    try:
                        cfp_curr = float(cfp_data[comp][c][columns[i]].values[0])
                    except:
                        cfp_curr = 0
                    cfp_past = 0
                    for n in range(1, cfp_diff+1):
                        cfp_past += float(cfp_data[comp][c][columns[i+n]].values[0])
                    if cfp_diff != 0:
                        cfp_avg = cfp_past/cfp_diff
                    else:
                        cfp_avg = 0
                    # get the cfp difference
                    cfp.append(cfp_curr - cfp_avg)
                    cfp_time.append(columns[i])
            # get temp difference
            temp = [a - b for a, b in zip(temp_curr_avg, temp_past_avg)]
        
            result[comp][c]["cfp_data"] = cfp
            result[comp][c]["climate_data"] = temp
            result[comp][c]["cfp_year"] = cfp_time
            result[comp][c]["climate_year"] = temp_time
            result[comp][c]['state'] = state
    return result   

def process_bushfire_pairs(cfp_data, state_data, bushfire_data, cfp_diff:int, climate_diff:int):
    """
    :cfp_data = 
    :state_data = 
    output = a nested dict, the key is the company name, and the value is a dictionary with the four keys: 
                "cfp_data", "climate_data", "cfp_year", "climate_year", and "state", 
                the "cfp_data" and "climate_data" will feed to correlation analysis
    """
    
    result = {}
    
    # shape data as year, cfp, bushfire
    for comp in cfp_data.keys():
        # init the values
        result[comp] = {}
        
        for c in CFP:
            result[comp][c] = {}
            cfp = []
            bushfire = []
            time = []
            state = state_data[comp]
            result[comp]['state'] = state

            for i in cfp_data[comp][c].iloc[:,range(1, cfp_data[comp][c].shape[1])]:
                # get the year of cfp dta
                year = i.split('/')[-1]
                try:
                    # get the corresponding year data of bushfire
                    bushfire_value = bushfire_data.loc[bushfire_data['Year'] == int(year)]['Acres']
                    # shape the string to int
                    bushfire_value = int(bushfire_value.values[0].replace(',', ''))
                    if bushfire_value:
                        cfp_value = cfp_data[comp][c][i][0]
                        cfp_value = float(cfp_value)
                        if cfp_value and cfp_value is not np.isnan(cfp_value):
                            cfp.append(cfp_value)
                            bushfire.append(bushfire_value)
                            time.append(i)
                except:
                    pass

            # compute the difference of cfp
            result[comp][c]["cfp_data"] = compute_diff(comp, cfp, cfp_diff, t=c)
            # compute the difference of cfp
            result[comp][c]["climate_data"] = compute_diff(comp, bushfire, climate_diff, t='bushfire')
            # reshape the time
            if cfp_diff == 0:
                result[comp][c]["cfp_year"] = time
            else:
                result[comp][c]["cfp_year"] = time[:-cfp_diff]
            if climate_diff == 0:
                result[comp][c]["climate_year"] = time
            else:
                result[comp][c]["climate_year"] = time[:-climate_diff]
    
    return result
        
def compute_diff(comp:str, data:list, time_diff:int, t:str):
    """
    output = processed data
    """
    
    result = []
    for i in range(len(data)-time_diff):
        current = data[i]
        # python follows left close and right open
        if time_diff == 0:
            result.append(current)
        else:
            moving_avg = sum(data[i+1:i+time_diff+1])/time_diff
            # remain 5 deciamls
            diff = round(current - moving_avg, 5)
            result.append(diff)
    if len(result) <= 5:
        print(comp, 'only has', len(result), 'data points after computing', 
              time_diff, 'years moving avg over', t, 'data')
        
    return result


def compute_p(data:dict, industry:str, climate:str, cfp_diff:int, climate_diff:int):
    """
    :data = a nested dictionary from process_data function
    """
    def cat_float(a:float, b:float) -> str:
        a = str(round(a, 3))
        b = str(round(b, 3))
        return a + '(' + b + ')'

    columns = pd.MultiIndex.from_product([['ROA1', 'ROA2', 'Operating Margin', 'Net Margin', 'Return On Equity', 
           'Current Ratio', 'Quick ratio', 'ROC', 'D/E ratio', 'EPS'], ['Pearson', 'Spearman', 'Kendall']],
                                        names = ["CFP", "Correlation"])
    index = pd.Index(data.keys(), name = "Company:")
    df = pd.DataFrame(columns = columns, index = index)
    
    for comp in data.keys():
        for c in CFP:
            print(comp,c)
            
            result = []
            l1 = data[comp][c]["cfp_data"]
            l2 = data[comp][c]["climate_data"]
            print(l1, l2)
            if len(l1) != l2:
                min_len = min(len(l1), len(l2))
                l1 = l1[:min_len]
                l2 = l2[:min_len]
            if len(l1) > 2:
                # Pearson correlation
                pearson = pearsonr(l1, l2)[0]
                p_p_value = pearsonr(l1, l2)[1]
#                 print(cat_float(pearson, p_p_value))
#                 df.loc[comp][c]["Pearson"] = cat_float(pearson, p_p_value)
                result.append(cat_float(pearson, p_p_value))
                # Spearman correlation
                spearman = spearmanr(l1, l2)[0]
                s_p_value = spearmanr(l1, l2)[1]
#                 print(cat_float(spearman, s_p_value))
#                 df.loc[comp][c]["Spearman"] = cat_float(spearman, s_p_value)
                result.append(cat_float(spearman, s_p_value))
                # Kendall correlation
                tau, k_p_value = kendalltau(l1, l2)
#                 print(cat_float(tau, k_p_value), '\n')
#                 df.loc[comp][c]["Kendall"] = cat_float(tau, k_p_value)
                result.append(cat_float(tau, k_p_value))
                df.loc[comp, c] = result
        
    title = 'The correlation result between '
    title += industry + '(' + str(cfp_diff) + ' years moving avg.)'
    title += ' and ' + climate + '(' + str(climate_diff) + ' years moving avg.).csv'
    df.to_csv(title)
    
    return df.style.set_caption(title)

# Bushfire

In [5]:
corr_ana("energy", 'bushfire', 0, 0)

PTEN only has 0 data points after computing 0 years moving avg over Operating Margin data
PTEN only has 0 data points after computing 0 years moving avg over bushfire data
PTEN only has 0 data points after computing 0 years moving avg over Net Margin data
PTEN only has 0 data points after computing 0 years moving avg over bushfire data
PTEN only has 0 data points after computing 0 years moving avg over Return On Equity data
PTEN only has 0 data points after computing 0 years moving avg over bushfire data
PTEN only has 0 data points after computing 0 years moving avg over Current Ratio data
PTEN only has 0 data points after computing 0 years moving avg over bushfire data
PTEN only has 0 data points after computing 0 years moving avg over Quick ratio data
PTEN only has 0 data points after computing 0 years moving avg over bushfire data
PTEN only has 0 data points after computing 0 years moving avg over D/E ratio data
PTEN only has 0 data points after computing 0 years moving avg over bushfire data
ICD only has 0 data points after computing 0 years moving avg over Operating Margin data
ICD only has 0 data points after computing 0 years moving avg over bushfire data
ICD only has 0 data points after computing 0 years moving avg over Net Margin data
ICD only has 0 data points after computing 0 years moving avg over bushfire data
ICD only has 0 data points after computing 0 years moving avg over Return On Equity data
ICD only has 0 data points after computing 0 years moving avg over bushfire data
ICD only has 0 data points after computing 0 years moving avg over Current Ratio data
ICD only has 0 data points after computing 0 years moving avg over bushfire data
ICD only has 0 data points after computing 0 years moving avg over Quick ratio data
ICD only has 0 data points after computing 0 years moving avg over bushfire data
ICD only has 0 data points after computing 0 years moving avg over D/E ratio data
ICD only has 0 data points after computing 0 years moving avg over bushfire data
HP only has 0 data points after computing 0 years moving avg over Operating Margin data
HP only has 0 data points after computing 0 years moving avg over bushfire data
HP only has 0 data points after computing 0 years moving avg over Net Margin data
HP only has 0 data points after computing 0 years moving avg over bushfire data
HP only has 0 data points after computing 0 years moving avg over Return On Equity data
HP only has 0 data points after computing 0 years moving avg over bushfire data
HP only has 0 data points after computing 0 years moving avg over Current Ratio data
HP only has 0 data points after computing 0 years moving avg over bushfire data
HP only has 0 data points after computing 0 years moving avg over Quick ratio data
HP only has 0 data points after computing 0 years moving avg over bushfire data
HP only has 0 data points after computing 0 years moving avg over D/E ratio data
HP only has 0 data points after computing 0 years moving avg over bushfire data
PTEN ROA1
[-0.243611758, -0.095887369, -0.058762134, 0.001026245, -0.083749539, -0.064960381, 0.030156409, 0.040111778, 0.0657193, 0.076366784, 0.03416329, -0.014383101, 0.127936754, 0.177932491, 0.30707096, 0.207564285, 0.082192226, 0.051426341, 0.002301304, 0.188769632, 0.057853897, -0.038510368, -0.001267963, 0.109251969, 0.048919226, 0.043378995, 0.078864353, 0.086956522, 0.007352941] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929]
PTEN ROA2
[-0.207707667, -0.085918324, -0.057249792, 0.001235954, -0.076430065, -0.059328351, 0.03227096, 0.040676812, 0.068227227, 0.084346859, 0.038434999, -0.014247524, 0.134054819, 0.188349963, 0.337615877, 0.239036109, 0.090658391, 0.054823298, 0.00239384, 0.256457444, 0.07344107, -0.038485938, -0.001364256, 0.152524906, 0.065299924, 0.050331126, 0.099800399, 0.1] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574]
PTEN Operating Margin
[] []
PTEN Net Margin
[] []
PTEN Return On Equity
[] []
PTEN Current Ratio
[] []
PTEN Quick ratio
[] []
PTEN ROC
[-0.273016, -0.110954, -0.069502, 0.001219, -0.111913, -0.086205, 0.041802, 0.054519, 0.08968, 0.10679, 0.045215, -0.018394, 0.163177, 0.225402, 0.400159, 0.272668, 0.107919, 0.067465, 0.002941, 0.238905, 0.072593, -0.044872, -0.001411, 0.130435, 0.062049, 0.055556, 0.116822, 0.126984, 0.012195] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929]
PTEN D/E ratio
[] []
PTEN EPS
[-2.965339, -1.580352, -1.202403, 0.022196, -1.66366, -1.546875, 0.859461, 1.00816, 1.627063, 1.758981, 0.644175, -0.211747, 1.926065, 2.849364, 4.300774, 2.161549, 0.645251, 0.341617, 0.013544, 1.066596, 0.319469, -0.139246, -0.004736, 0.358446, 0.108718, 0.074335, 0.118596, 0.083857, 0.008609] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929]
ICD ROA1
[-0.233872, -0.117578, -0.034184, -0.079758, -0.073411, -0.025033, -0.097283, -0.010796, -0.029552] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238]
ICD ROA2
[-0.207776739, -0.110336766, -0.044952991, -0.080092031, -0.071901909, -0.026078208, -0.118723328, -0.011333583] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546]
ICD Operating Margin
[] []
ICD Net Margin
[] []
ICD Return On Equity
[] []
ICD Current Ratio
[] []
ICD Quick ratio
[] []
ICD ROC
[-0.245731, -0.129145, -0.038291, -0.085169, -0.078155, -0.026672, -0.10865, -0.012129, -0.034195] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238]
ICD D/E ratio
[] []
ICD EPS
[-15.451212, -15.682386, -5.152916, -12.705866, -11.724553, -6.422194, -22.794882] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613]
HP ROA1
[-0.102388365, -0.005763492, 0.077664092, -0.019908733, -0.008317893, 0.059035835, 0.105434938, 0.117583295, 0.101562029, 0.086769676, 0.036646762, 0.084965864, 0.128687907, 0.155703135, 0.137656977, 0.076716265, 0.003098425, 0.012623646, 0.051752894, 0.105718769, 0.065343805, 0.038568983, 0.092809978, 0.081462848, 0.088210245, 0.01379893, 0.040012804, 0.040268456, 0.018445773, 0.036856745, 0.081660662, 0.038396482, 0.035039029, 0.038508664, 0.012428977, 0.030032468] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929, 2953578, 4621621, 1827310, 5009290, 2447296, 2719162, 2896147]
HP ROA2
[-0.092696728, -0.005584027, 0.076282502, -0.019320665, -0.008127556, 0.060866205, 0.109145457, 0.122917472, 0.108353622, 0.093682981, 0.037100568, 0.091248381, 0.142656719, 0.178985558, 0.154741023, 0.083125692, 0.003088555, 0.013524025, 0.049013435, 0.109949737, 0.069475163, 0.038907322, 0.095291902, 0.090757208, 0.094641342, 0.014681648, 0.040462896, 0.04112337, 0.01860946, 0.036611692, 0.081083383, 0.038879849, 0.03519777, 0.038783605, 0.011872456] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929, 2953578, 4621621, 1827310, 5009290, 2447296, 2719162]
HP Operating Margin
[] []
HP Net Margin
[] []
HP Return On Equity
[] []
HP Current Ratio
[] []
HP Quick ratio
[] []
HP ROC
[-0.12862483, -0.007493133, 0.098975066, -0.027528114, -0.011246896, 0.077772307, 0.14257137, 0.158801973, 0.142762969, 0.119939327, 0.049349243, 0.110206985, 0.166860665, 0.198742676, 0.185327693, 0.099751571, 0.00391254, 0.01557898, 0.063825276, 0.13400565, 0.081833305, 0.047392315, 0.113976799, 0.107179226, 0.111367127, 0.016777949, 0.047682624, 0.047472019, 0.021483986, 0.042510527, 0.094108343, 0.044137663, 0.040055523, 0.044141252, 0.014242116, 0.035700502] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929, 2953578, 4621621, 1827310, 5009290, 2447296, 2719162, 2896147]
HP D/E ratio
[] []
HP EPS
[-4.409185095, -0.300284808, 4.309226652, -1.14519095, -0.510124121, 3.804255659, 6.413247186, 6.774403531, 5.400102226, 4.048600701, 1.460069683, 3.302371771, 4.312974407, 4.341317558, 2.829117375, 1.228526113, 0.043205098, 0.178229659, 0.635034484, 1.446799464, 0.823321556, 0.431225567, 1.024644108, 0.841528744, 0.728321144, 0.098929941, 0.252934035, 0.249624548, 0.109863281, 0.198027201, 0.486011844, 0.234775774, 0.188686295, 0.205499925, 0.065454817, 0.183925873] [10122336, 4664364, 8767492, 10026086, 5509995, 10125149, 3595613, 4319546, 9326238, 8711367, 3422724, 5921786, 5292468, 9328045, 9873745, 8689389, 8097880, 3960842, 7184712, 3570911, 7393493, 5626093, 1329704, 2856959, 6065998, 1840546, 4073579, 1797574, 2069929, 2953578, 4621621, 1827310, 5009290, 2447296, 2719162, 2896147]

In [26]:
corr_ana("energy", 'bushfire', 'ROA1', 0, 0)

In [93]:
corr_ana("travel", 'bushfire', 'ROA2', 0, 5)

NCLH only has 0 data points after computing 0 years moving avg over cfp data
NCLH only has 0 data points after computing 5 years moving avg over bushfire data
LIND only has 4 data points after computing 5 years moving avg over bushfire data

/Users/dnhb/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:329: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

In [32]:
corr_ana("agriculture", 'bushfire', 'ROA1', 0, 3)

CTA-PB only has 0 data points after computing 0 years moving avg over cfp data
CTA-PB only has 0 data points after computing 3 years moving avg over bushfire data
CTVA only has 0 data points after computing 0 years moving avg over cfp data
CTVA only has 0 data points after computing 3 years moving avg over bushfire data
CTA-PA only has 0 data points after computing 0 years moving avg over cfp data
CTA-PA only has 0 data points after computing 3 years moving avg over bushfire data

/Users/dnhb/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:329: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

In [59]:
corr_ana("travel", 'bushfire', 'ROA1', 0, 0)

NCLH only has 0 data points after computing 0 years moving avg over cfp data
NCLH only has 0 data points after computing 0 years moving avg over bushfire data

/Users/dnhb/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:329: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

# Appendix

## Person

$$
r=\frac{\sum\left(x-m_{x}\right)\left(y-m_{y}\right)}{\sqrt{\sum\left(x-m_{x}\right)^{2} \sum\left(y-m_{y}\right)^{2}}}
$$

REF: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html

## Spearman

$$
\rho=1-\frac{6 \sum d_{i}^{2}}{n\left(n^{2}-1\right)}
$$

$\rho$ 	=	Spearman's rank correlation coefficient  
$d_i$ = difference between the two ranks of each observation  
$n$ = number of observations

REF1: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html  
REF2: https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient

## Kendall

$$
\tau=\frac{(\text { number of concordant pairs })-(\text { number of discordant pairs })}{\left(\begin{array}{c}
n \\
2
\end{array}\right)}
$$

REF: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html?highlight=kendall#scipy.stats.kendalltau